# fly.toml app configuration file generated for go-jereko-api on 2024-04-10T11:24:51+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'go-jereko-api'
primary_region = 'ams'

[build]
  dockerfile = "Dockerfile"

[build.args]
  PORT = "8080"
  GIN_MODE = "release"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = "8080"
  GIN_MODE = "release"